source 'https://rubygems.org'

# Specify your gem's dependencies in cloudpassage.gemspec
gemspec
gem 'rest-client', '>= 1.6.7'
gem 'oauth', '>=0.5.1'
gem 'json', '>=1.8.1'
gem 'parallel', '>=1.9.0'
gem 'activesupport', '>=5.0.0.1'
gem 'rubocop'
